### ISSUE TITLE
Update example to use sequelize v4

### ISSUE THREAD

**Issue by janmeier** [sequelize/express-example#67]

**Comment by rolele** [comment]
It would be great because of the breaking changes from v3 to v4.
Many comments on the internet does not work anymore with the current version of sequelize.

**Comment by jljorgenson18** [comment]
+1 For those that used this example in v3, there isn't a great way to upgrade yet.

**Comment by randomor** [comment]
As a first time user of Sequelize.js, I do find the v4 documentation very lacking on the ES6 part. The main repo issue https://github.com/sequelize/sequelize/issues/6524 was often referred as documentation while it reads as a proposal. There are several questions a new user has to answer:

- How to do the ES6 class syntax with instance/class method?
- How to organize the files in their own directory and be imported in one `index.js`
- How to do the `sequelize.import`?

Since this repo is linked by the main repo, I think it will be very helpful if someone who has successfully used ES6 and V4 to redo this example.

**Comment by n-davis** [comment]
Up vote.

**Comment by shaishab** [comment]
I have created a project using Express and Sequelize v4 and used PostgreSQL as database. The project link 

https://github.com/shaishab/sequelize-express-example

**Comment by Sha-Grisha** [comment]
Sequelize 5 is coming, but there is no express example for sequelize 4?

**Comment by tvl83** [comment]
I came here for an example of v5 and it's for 3x. Very disappointing that it's linked from docs and not updated. :(

**Comment by papb** [comment]
Modern example created with Sequelize v6, finally :tada:
